public enum Requete {
    CLIENT_DEMANDER_CLE_PUBLIQUE,
    CLIENT_VOTER,
    CLIENT_DEMANDER_VOTE_EN_COURS,

    SERVEUR_DEMANDER_CLE_PUBLIQUE,
    SERVEUR_CREER_VOTE,
    SERVEUR_DEMANDER_DECHIFFREMENT
}
